function generateExcelFile(fileNameStroopPerf, fileNameStroopBlocks,...
    fileNameNbackPerf, fileNameNbackBlock)
    files = dir('*.xdf');
    dataTableNback = {'subId', 'time', 'rt',...
    'condition', 'isPractice', 'isSuccess', 'blockNumber',...
    'n', 'stimulus', 'order', 'responseType'};
    dataTableStroop = {'subId', 'time', 'rt',...
    'condition', 'isPractice', 'isSuccess','blockNumber'...
    'stroopCondition', 'stimulus', 'order'};
    blockTimesNback = {'nLevel', 'isPractice',...
       'condition', 'blockNumber', 'startTime', 'endTime',...
       'instructionsLength', 'fixationLength',...
       'afterFixationLength', 'subId', 'order'};
    blockTimesStroop = {'isCongruent', 'isPractice',...
       'condition', 'blockNumber', 'startTime', 'endTime',...
       'instructionsLength', 'fixationLength',...
       'afterFixationLength', 'subId', 'order'};
    for file = files'
        data = load_xdf(file.name);
        times = {};
        markers = {};
        for n = 1:numel(data)
            if string(data{1,n}.info.name) == "MyMarkerStream"
                times = data{1,n}.time_stamps;
                markers = data{1,n}.time_series;
                [dataTableNbackRes blockTimesNbackRes dataTableStroopRes...
                    blockTimesStroopRes] = organize_data_basic...
                    (times, markers, extractBefore(string(file.name), "."));
                dataTableNback = [dataTableNback;dataTableNbackRes];
                blockTimesNback = [blockTimesNback;blockTimesNbackRes];
                dataTableStroop = [dataTableStroop;dataTableStroopRes];
                blockTimesStroop = [blockTimesStroop;blockTimesStroopRes];
            end
        end
    end
    xlswrite(fileNameNbackPerf,dataTableNback);
    xlswrite(fileNameStroopPerf,dataTableStroop);
    xlswrite(fileNameNbackBlock,blockTimesNback);
    xlswrite(fileNameStroopBlocks,blockTimesStroop);

end